### ISSUE TITLE
运行报错？

### ISSUE THREAD

**Issue by fauns-o** [Peony2022/shiro_killer#5]
worker exits from a panic: runtime error: invalid memory address or nil pointer dereference
 worker exits from panic: goroutine 25 [running]:
github.com/panjf2000/ants.(*goWorker).run.func1.1()
        /root/go/pkg/mod/github.com/panjf2000/ants@v1.3.0/worker.go:59 +0xe5
panic({0x62a8a0, 0x848110})
        /usr/lib/go-1.17/src/runtime/panic.go:1038 +0x215
main.AesCbcEncrypt({0xc000b84050, 0x6677ed, 0xc00001a0c0}, {0xc0001ec100, 0x70, 0x72})
        /home/kali/desktop/4_POC/shiro/shiro_killer/encrypt.go:23 +0x58

**Comment by ltfafei** [comment]
对哦，我也是这个报错：

![image](https://user-images.githubusercontent.com/43526141/180594154-bea9a2c7-4d25-47ac-90a8-f215110083bd.png)

**Comment by Peony2022** [comment]
感谢提交issues，已更新
